#!/bin/bash

#### Build script ####

echo " /


██      ███████ ██ ██████      ██████  ██    ██ ██ ██      ██████      ███████  ██████ ██████  ██ ██████  ████████ 
██      ██      ██ ██   ██     ██   ██ ██    ██ ██ ██      ██   ██     ██      ██      ██   ██ ██ ██   ██    ██    
██      ███████ ██ ██   ██     ██████  ██    ██ ██ ██      ██   ██     ███████ ██      ██████  ██ ██████     ██    
██           ██ ██ ██   ██     ██   ██ ██    ██ ██ ██      ██   ██          ██ ██      ██   ██ ██ ██         ██    
███████ ███████ ██ ██████      ██████   ██████  ██ ███████ ██████      ███████  ██████ ██   ██ ██ ██         ██    
                    A tool to build our projects and publish them to Github faster                                                                                  
                                                                                                                   "

echo "staging changes..."
git add -A
echo "commiting..."
git commit -m "$1"
echo "\n Do you want to push the changes? [Y|N] "
read tpush

if  [[ $tpush == 'y' || $tpush == 'Y' ]] ; then
    echo "Pushing changes to origin/master..."
    git push
    fi

echo "\n Operation Finished, Bravo Six going dark"
exit 0
